name: Update Languages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-languages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch languages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Store your token in GitHub Secrets
        run: |
          import requests
          import os
          
          username = os.getenv('GITHUB_ACTOR')
          token = os.getenv('PERSONAL_ACCESS_TOKEN')
          headers = {'Authorization': f'token {token}'}
          repos_url = f'https://api.github.com/users/{username}/repos?per_page=100'
          
          response = requests.get(repos_url, headers=headers)
          repos = response.json()
          
          languages = set()
          for repo in repos:
              lang_url = repo['languages_url']
              lang_response = requests.get(lang_url, headers=headers)
              repo_languages = lang_response.json()
              languages.update(repo_languages.keys())
          
          with open('languages.txt', 'w') as f:
              f.write(', '.join(languages))

      - name: Update README
        run: |
          languages = ''
          with open('languages.txt', 'r') as f:
              languages = f.read().strip()
          
          with open('README.md', 'r') as f:
              content = f.readlines()
          
          for i, line in enumerate(content):
              if line.startswith('## Languages'):
                  content[i + 1] = f'``````\n'
                  break

          with open('README.md', 'w') as f:
              f.writelines(content)

      - name: Commit changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add README.md languages.txt
          git commit -m "Update languages in README"
          git push
